site_name: Komprese stromových struktur
repo_url: https://github.com/Bercek71/tree-compression
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
  features:
    - navigation.tabs
    - search.highlight
    - search
    - toc.integrate
    - sticky-navigation
    - navigation.sections

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css

nav:
  - <i class="fas fa-home"></i> Home: index.md
  - <i class="fas fa-project-diagram"></i> Architektura: architecture.md
  - <i class="fas fa-cogs"></i> Požadavky: requirements.md
  - Deník projektu:
      - <i class="fas fa-book"></i> Deník: journal.md
      - <i class="fas fa-calendar-day"></i> 2025-02-19: journal/2025-02-19.md
      - <i class="fas fa-calendar-day"></i> 2025-02-20: journal/2025-02-20.md
      - <i class="fas fa-calendar-day"></i> 2025-02-23: journal/2025-02-23.md
      - <i class="fas fa-calendar-day"></i> 2025-03-10: journal/2025-03-10.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.details