name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Build the site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        mv site/* .
        git add -A
        git commit -m "Deploy site to GitHub Pages"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Bercek71/tree-compression.git
        git push --force origin gh-pages
