name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # Spustí se, když provedeš změny na větvi main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install MkDocs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Build the site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Větev pro GitHub Pages
        folder: site  # MkDocs generuje statickou stránku do složky 'site'
        token: ${{ secrets.GITHUB_TOKEN }}  # Automaticky vytvořený token pro přístup do repozitáře
