name: Tree Compression Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dotnet-coverage tool
        run: dotnet tool install --global dotnet-coverage

      - name: Restore dependencies
        run: dotnet restore TreeCompresion.sln
        
      - name: Build
        run: dotnet build TreeCompresion.sln --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          mkdir -p TestResults
          
          # Run tests with coverage
          dotnet-coverage collect --output TestResults/coverage.cobertura.xml --output-format cobertura \
            "dotnet test src/Tests/Tests.csproj --configuration Release"
          
          # If we need to merge multiple coverage files in the future, we can uncomment this
          # dotnet-coverage merge -o TestResults/merged-coverage.cobertura.xml -f cobertura TestResults/coverage.cobertura.xml

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: 'TestResults/coverage.cobertura.xml'
          targetdir: 'TestResults/CoverageReport'
          reporttypes: 'HtmlInline;Cobertura'

      - name: Upload test results and coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-results-and-coverage
          path: TestResults